#####  3월 6일 넘파이 연습

####  넘파이 생성과 reshpae 함수

In [2]:
import numpy as np

In [12]:
a=np.array([[1,2,3],[4,5,6]])

In [13]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
b=np.arange(10)  # 10개의 1차원 테이블 생성

In [18]:
np.ones((3,2),dtype='int32')  #1로만 이루어신 테이블 생성

array([[1, 1],
       [1, 1],
       [1, 1]])

In [21]:
np.zeros((3,2),dtype='int32') # 제로 테이블 생성

array([[0, 0],
       [0, 0],
       [0, 0]])

In [26]:
re_b=b.reshape(2,5)  #reshape 함수  2행 5열로 바꿈

In [27]:
re_b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
b.reshape(-1,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
b.reshape(-2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
c=np.arange(5)

In [34]:
c  # 1차원 데이터

array([0, 1, 2, 3, 4])

In [39]:
re_c=c.reshape(-1,1) ##2차원 테이블 로 변환


In [40]:
re_c  #2차원 테이블

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
re_c.reshape(-1,)

## 넘파이 인덱싱

In [65]:
a=np.arange(9)

In [67]:
a=a.reshape(3,3)

In [79]:
a

array([[0, 0, 0],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
a

array([[0, 0, 0],
       [3, 4, 5],
       [6, 7, 8]])

In [81]:
a[0,1]=1
a[0,2]=2

In [82]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

###### 슬라이싱  (연속된 값을 가져온다)

In [83]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [84]:
a[0:2,0:2]

array([[0, 1],
       [3, 4]])

In [85]:
a[:]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

####  팬시 인덱싱   방안에 있는 데이터를 출력해줌

In [88]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [89]:
a[[0,1],2]

array([2, 5])

In [90]:
a[1,0:2]

array([3, 4])

In [91]:
a[1,[0,1]]

array([3, 4])

In [92]:
f=np.arange(start=1,stop=10)

In [93]:
f

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 불린 인덱싱
#####  조건 필터링과 검색을 동시에 가능해서 자주 사용된다.
#####  ndarray내의 값이 5보다 큰 ndarray를 추출하고자 한다면?

In [105]:
g=a[a>5]    # 어레이 안에서 5보다 큰 데이터를 출력
g
print(g)

[6 7 8]


In [102]:
a>5 # true false 형태로 출력

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [96]:
b=np.arange(10)

In [97]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
print(b>5)

[False False False False False False  True  True  True  True]


# 3월 10일   정렬 함수

In [4]:
aa=np.array([3,1,9,5])

In [5]:
aa

array([3, 1, 9, 5])

In [6]:
np.sort(aa)   #np.sort는 출력값만 정령해주고 원래 np는 정렬이 되지 않는다.

array([1, 3, 5, 9])

In [7]:
aa

array([3, 1, 9, 5])

In [15]:
bb=np.array([2,3,4,1])

In [16]:
bb

array([2, 3, 4, 1])

In [17]:
bb.sort() # ndarray.sort 는 출력값을 none값으로 반환하고 원래 값은 정렬이 된다.

In [19]:
cc=bb.sort()

In [21]:
print('cc값은?:',cc)  # ndarray.sort의 반환값은 none

cc값은?: None


In [22]:
np.sort(aa)[::-1]   #내림차순 정리

array([9, 5, 3, 1])

In [28]:
qq=np.array([[9,1],[2,4]])

In [29]:
qq

array([[9, 1],
       [2, 4]])

In [30]:
np.sort(qq,axis=0)    #로우 방향 정렬

array([[2, 1],
       [9, 4]])

In [31]:
np.sort(qq,axis=1)   #컬럼 방향 정렬

array([[1, 9],
       [2, 4]])

* argsort

In [35]:
ori=np.array([3,1,9,5])

In [36]:
re=np.argsort(ori)  ## argsort의 정렬 반환 값은 방번호를 반환

In [37]:
re

array([1, 0, 3, 2], dtype=int64)

* argsort 이거대체 왜씀?  아래 예시

In [40]:
name=np.array(['a','c','r'])

In [41]:
num=np.array([10,30,23])

In [46]:
num_sort=np.argsort(num)
num_sort

array([0, 2, 1], dtype=int64)

In [47]:
name_sort=name[num_sort]
name_sort

array(['a', 'r', 'c'], dtype='<U1')

In [49]:
number=num[num_sort]
number

array([10, 23, 30])

In [50]:
* 행렬 연산

SyntaxError: invalid syntax (<ipython-input-50-772fc3d0fbbe>, line 1)